#:schema node_modules/@deco/workers-runtime/config-schema.json
name = "mcp-previsao"
main = "main.ts"
compatibility_date = "2025-06-17"
compatibility_flags = [ "nodejs_compat" ]
scope = "superafonso"

[assets]
directory = "./view-build"
binding = "ASSETS"

[deco]
workspace = "superafonso"
bindings = []
enable_workflows = true
local = false

[[migrations]]
tag = "v1"
new_classes = [ "Workflow" ]

[durable_objects]
[[durable_objects.bindings]]
name = "DECO_CHAT_WORKFLOW_DO"
class_name = "Workflow"

[env]
[env.production]
[env.production.vars]
BRASIL_API_BASE_URL = "https://brasilapi.com.br/api"
BRASIL_API_ZIPCODE_LOOKUP = "/cep/v1"
BRASIL_API_WEATHER_FORECAST = "/cptec/v1/clima/previsao"
BRASIL_API_CITY_SEARCH = "/cptec/v1/cidade"

[env.development]
[env.development.vars]
BRASIL_API_BASE_URL = "https://brasilapi.com.br/api"
BRASIL_API_ZIPCODE_LOOKUP = "/cep/v1"
BRASIL_API_WEATHER_FORECAST = "/cptec/v1/clima/previsao"
BRASIL_API_CITY_SEARCH = "/cptec/v1/cidade"

[[rules]]
type = "Text"
globs = [ "**/*.sql" ]
fallthrough = true